# Generated by Django 5.2.7 on 2025-10-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(help_text='O e-mail que será usado como remetente para comunicações do sistema, como redefinição de senha.', max_length=254, verbose_name='E-mail Remetente Padrão')),
            ],
            options={
                'verbose_name': 'Configuração Operacional',
                'verbose_name_plural': 'Configurações Operacionais',
            },
        ),
    ]
