# Generated by Django 5.2.7 on 2025-10-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalsettings',
            name='company_name',
            field=models.CharField(default='SistemasBr', max_length=255, verbose_name='Nome da Empresa'),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='email_host',
            field=models.CharField(blank=True, max_length=255, verbose_name='Servidor SMTP (Host)'),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='Senha SMTP'),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=255, verbose_name='Usuário SMTP'),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='email_port',
            field=models.PositiveIntegerField(blank=True, default=587, verbose_name='Porta SMTP'),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='email_use_ssl',
            field=models.BooleanField(default=False, verbose_name='Usar SSL'),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='email_use_tls',
            field=models.BooleanField(default=True, verbose_name='Usar TLS'),
        ),
    ]
