# Generated by Django 5.2.7 on 2025-10-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_operationalsettings_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalsettings',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Logo que aparecerá no cabeçalho.', null=True, upload_to='logos/', verbose_name='Logo da Empresa'),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail de Contato Público'),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='enable_feedback_system',
            field=models.BooleanField(default=True, help_text='Permite que usuários enviem feedback nos artigos.', verbose_name='Habilitar Sistema de Feedback'),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='enable_public_registration',
            field=models.BooleanField(default=False, help_text='Permite que novos usuários se cadastrem no sistema.', verbose_name='Habilitar Cadastro Público'),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Ícone que aparece na aba do navegador.', null=True, upload_to='logos/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='footer_text',
            field=models.CharField(blank=True, help_text='Ex: © 2024 Nome da Empresa. Todos os direitos reservados.', max_length=255, verbose_name='Texto do Rodapé'),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Ex: UA-12345678-1', max_length=50, verbose_name='ID do Google Analytics'),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='privacy_policy_url',
            field=models.URLField(blank=True, verbose_name='URL da Política de Privacidade'),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='terms_of_service_url',
            field=models.URLField(blank=True, verbose_name='URL dos Termos de Serviço'),
        ),
        migrations.AlterField(
            model_name='operationalsettings',
            name='sender_email',
            field=models.EmailField(help_text='O e-mail que será usado como remetente para comunicações do sistema.', max_length=254, verbose_name='E-mail Remetente Padrão'),
        ),
    ]
