# Generated by Django 5.2.6 on 2025-09-26 20:36

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Admin da KB SistemasBr', max_length=255)),
                ('site_header', models.CharField(default='KB SistemasBr', max_length=255)),
                ('site_brand', models.CharField(default='KB SistemasBr', max_length=255)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='visual/')),
                ('login_logo', models.ImageField(blank=True, null=True, upload_to='visual/')),
                ('welcome_sign', models.CharField(default='Bem-vindo ao painel de administração da KB da SistemasBr', max_length=255)),
                ('copyright', models.CharField(default='SistemasBr', max_length=255)),
            ],
            options={
                'verbose_name': 'Aparência do Painel Administrativo',
                'verbose_name_plural': 'Aparência do Painel Administrativo',
            },
        ),
        migrations.CreateModel(
            name='SiteAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SistemasBr KB', max_length=255)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='visual/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='visual/')),
                ('primary_color', colorfield.fields.ColorField(default='#1C85E8', image_field=None, max_length=25, samples=None)),
                ('secondary_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('background_color', colorfield.fields.ColorField(default='#F4F4F4', image_field=None, max_length=25, samples=None)),
                ('text_color', colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'verbose_name': 'Aparência do Site',
                'verbose_name_plural': 'Aparência do Site',
            },
        ),
    ]
