# Generated by Django 5.2.6 on 2025-09-26 20:50

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminappearance',
            options={'verbose_name': 'Admin Panel Appearance', 'verbose_name_plural': 'Admin Panel Appearance'},
        ),
        migrations.AlterModelOptions(
            name='siteappearance',
            options={'verbose_name': 'Site Appearance', 'verbose_name_plural': 'Site Appearance'},
        ),
        migrations.AddField(
            model_name='adminappearance',
            name='accent_color',
            field=colorfield.fields.ColorField(default='#17a2b8', image_field=None, max_length=25, samples=None, verbose_name='Accent Color'),
        ),
        migrations.AddField(
            model_name='adminappearance',
            name='custom_css',
            field=models.TextField(blank=True, null=True, verbose_name='Custom CSS'),
        ),
        migrations.AddField(
            model_name='adminappearance',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None, verbose_name='Primary Color'),
        ),
        migrations.AddField(
            model_name='adminappearance',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#6c757d', image_field=None, max_length=25, samples=None, verbose_name='Secondary Color'),
        ),
        migrations.AddField(
            model_name='adminappearance',
            name='sidebar_color',
            field=colorfield.fields.ColorField(default='#343a40', image_field=None, max_length=25, samples=None, verbose_name='Sidebar Color'),
        ),
        migrations.AddField(
            model_name='adminappearance',
            name='sidebar_link_color',
            field=colorfield.fields.ColorField(default='#ced4da', image_field=None, max_length=25, samples=None, verbose_name='Sidebar Link Color'),
        ),
        migrations.AddField(
            model_name='adminappearance',
            name='sidebar_text_color',
            field=colorfield.fields.ColorField(default='#adb5bd', image_field=None, max_length=25, samples=None, verbose_name='Sidebar Text Color'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='button_border_radius',
            field=models.CharField(default='0.25rem', max_length=10, verbose_name='Button Border Radius'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='button_primary_bg_color',
            field=colorfield.fields.ColorField(default='#1C85E8', image_field=None, max_length=25, samples=None, verbose_name='Primary Button BG Color'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='button_primary_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Primary Button Text Color'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='button_secondary_bg_color',
            field=colorfield.fields.ColorField(default='#6c757d', image_field=None, max_length=25, samples=None, verbose_name='Secondary Button BG Color'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='button_secondary_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Secondary Button Text Color'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='custom_css',
            field=models.TextField(blank=True, null=True, verbose_name='Custom CSS'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='font_family_base',
            field=models.CharField(default='"Helvetica Neue", Helvetica, Arial, sans-serif', max_length=255, verbose_name='Base Font Family'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='font_family_headings',
            field=models.CharField(default='"Helvetica Neue", Helvetica, Arial, sans-serif', max_length=255, verbose_name='Headings Font Family'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='font_size_base',
            field=models.CharField(default='16px', max_length=10, verbose_name='Base Font Size'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='font_size_h1',
            field=models.CharField(default='2.5rem', max_length=10, verbose_name='H1 Font Size'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='font_size_h2',
            field=models.CharField(default='2rem', max_length=10, verbose_name='H2 Font Size'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='font_size_h3',
            field=models.CharField(default='1.75rem', max_length=10, verbose_name='H3 Font Size'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='footer_background_color',
            field=colorfield.fields.ColorField(default='#343a40', image_field=None, max_length=25, samples=None, verbose_name='Footer Background Color'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='footer_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Footer Text Color'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='header_background_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Header Background Color'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='header_text_color',
            field=colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Header Text Color'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='heading_color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None, verbose_name='Heading Color'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='link_color',
            field=colorfield.fields.ColorField(default='#1C85E8', image_field=None, max_length=25, samples=None, verbose_name='Link Color'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='link_hover_color',
            field=colorfield.fields.ColorField(default='#1565C0', image_field=None, max_length=25, samples=None, verbose_name='Link Hover Color'),
        ),
        migrations.AlterField(
            model_name='adminappearance',
            name='copyright',
            field=models.CharField(default='SistemasBr', max_length=255, verbose_name='Copyright'),
        ),
        migrations.AlterField(
            model_name='adminappearance',
            name='login_logo',
            field=models.ImageField(blank=True, null=True, upload_to='visual/admin/', verbose_name='Login Logo'),
        ),
        migrations.AlterField(
            model_name='adminappearance',
            name='site_brand',
            field=models.CharField(default='KB SistemasBr', max_length=255, verbose_name='Site Brand'),
        ),
        migrations.AlterField(
            model_name='adminappearance',
            name='site_header',
            field=models.CharField(default='KB SistemasBr', max_length=255, verbose_name='Site Header'),
        ),
        migrations.AlterField(
            model_name='adminappearance',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Must be 40px in height', null=True, upload_to='visual/admin/', verbose_name='Site Logo'),
        ),
        migrations.AlterField(
            model_name='adminappearance',
            name='site_title',
            field=models.CharField(default='Admin da KB SistemasBr', max_length=255, verbose_name='Site Title'),
        ),
        migrations.AlterField(
            model_name='adminappearance',
            name='welcome_sign',
            field=models.CharField(default='Bem-vindo ao painel de administração', max_length=255, verbose_name='Welcome Sign'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='background_color',
            field=colorfield.fields.ColorField(default='#F4F4F4', image_field=None, max_length=25, samples=None, verbose_name='Background Color'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='visual/', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#1C85E8', image_field=None, max_length=25, samples=None, verbose_name='Primary Color'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Secondary Color'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='visual/', verbose_name='Site Logo'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='site_name',
            field=models.CharField(default='SistemasBr KB', max_length=255, verbose_name='Site Name'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='text_color',
            field=colorfield.fields.ColorField(default='#333333', image_field=None, max_length=25, samples=None, verbose_name='Body Text Color'),
        ),
    ]
