# Generated by Django 5.2.7 on 2025-10-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0002_alter_adminappearance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminappearance',
            name='sidebar_link_color',
        ),
        migrations.AddField(
            model_name='adminappearance',
            name='admin_email',
            field=models.EmailField(default='admin@sistemasbr.com', help_text='Email for users to contact in case of issues.', max_length=255, verbose_name='Admin Contact Email'),
        ),
    ]
