# Generated by Django 5.2.7 on 2025-10-13 18:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0003_remove_adminappearance_sidebar_link_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminappearance',
            name='sidebar_link_color',
            field=colorfield.fields.ColorField(default='#ced4da', image_field=None, max_length=25, samples=None, verbose_name='Sidebar Link Color'),
        ),
    ]
