# Generated by Django 5.2.7 on 2025-10-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0004_adminappearance_sidebar_link_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteappearance',
            name='button_border_radius',
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='footer_facebook_link',
            field=models.URLField(blank=True, default='https://www.facebook.com/sistemasbr.net/?locale=pt_BR', verbose_name='Footer Facebook Link'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='footer_instagram_link',
            field=models.URLField(blank=True, default='https://www.instagram.com/sistemasBR/', verbose_name='Footer Instagram Link'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='footer_linkedin_link',
            field=models.URLField(blank=True, default='https://br.linkedin.com/company/sistemasbr', verbose_name='Footer LinkedIn Link'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='footer_support_title',
            field=models.CharField(blank=True, default='Suporte Técnico', max_length=100, verbose_name='Footer Support Title'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='footer_whatsapp_link',
            field=models.URLField(blank=True, default='https://wa.me/1736223222', verbose_name='Footer WhatsApp Link'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='footer_whatsapp_text',
            field=models.CharField(blank=True, default='17 3622-3222', max_length=50, verbose_name='Footer WhatsApp Text'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='footer_youtube_link',
            field=models.URLField(blank=True, default='https://www.youtube.com/user/sistemasbr', verbose_name='Footer YouTube Link'),
        ),
    ]
