# Generated by Django 5.2.6 on 2025-12-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0005_remove_siteappearance_button_border_radius_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteappearance',
            name='font_family_base',
            field=models.CharField(default='Helvetica Neue, Helvetica, Arial, sans-serif', max_length=255, verbose_name='Base Font Family'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='font_family_headings',
            field=models.CharField(default='Helvetica Neue, Helvetica, Arial, sans-serif', max_length=255, verbose_name='Headings Font Family'),
        ),
    ]
