# Generated by Django 5.2.6 on 2025-09-12 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria.', max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional da categoria.')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do artigo.', max_length=200)),
                ('conteudo', models.TextField(help_text='Conteúdo do artigo em formato de texto.')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, help_text='Data de publicação do artigo.')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da última atualização do artigo.')),
                ('categoria', models.ForeignKey(help_text='Categoria à qual o artigo pertence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos', to='kb.categoria')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
