# Generated by Django 5.2.6 on 2025-09-15 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Categoria pai, se for uma sub-categoria.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='kb.categoria'),
        ),
    ]
