# Generated by Django 5.2.6 on 2025-09-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_categoria_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='conteudo',
            field=models.TextField(help_text='Conteúdo do artigo.'),
        ),
    ]