# Generated by Django 5.2.6 on 2025-09-15 19:14

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_alter_artigo_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='conteudo',
            field=tinymce.models.HTMLField(help_text='Conteúdo do artigo.'),
        ),
    ]
