# Generated by Django 5.2.6 on 2025-09-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0004_alter_artigo_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icon',
            field=models.CharField(blank=True, help_text='Classe do ícone Font Awesome (ex: fa-solid fa-book).', max_length=50),
        ),
    ]
