# Generated by Django 5.2.6 on 2025-09-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0006_artigo_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Ordem de exibição da categoria.'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(help_text='Nome da categoria.', max_length=100),
        ),
    ]
