# Generated by Django 5.2.6 on 2025-09-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0007_alter_categoria_options_categoria_ordem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigo',
            options={'ordering': ['ordem', 'titulo'], 'verbose_name': 'Artigo', 'verbose_name_plural': 'Artigos'},
        ),
        migrations.AddField(
            model_name='artigo',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Ordem de exibição do artigo.'),
        ),
    ]
