# Generated by Django 5.2.6 on 2025-09-25 13:00

from django.db import migrations

def create_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('kb', 'Profile')
    for user in User.objects.filter(profile__isnull=True):
        Profile.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0010_alter_feedback_options_alter_feedback_artigo_and_more'),
    ]

    operations = [
        migrations.RunPython(create_profiles),
    ]
