# Generated by Django 5.2.7 on 2025-10-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0011_auto_20250925_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigável gerada a partir do título.', max_length=255, null=True, unique=True),
        ),
    ]
