# Generated by Django 5.0.6 on 2024-05-24 14:30

from django.db import migrations
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Artigo = apps.get_model('kb', 'Artigo')
    for artigo in Artigo.objects.all():
        if not artigo.slug:
            artigo.slug = slugify(artigo.titulo)
            # Lógica para garantir unicidade, similar ao método save
            original_slug = artigo.slug
            counter = 1
            while Artigo.objects.filter(slug=artigo.slug).exclude(pk=artigo.pk).exists():
                artigo.slug = f'{original_slug}-{counter}'
                counter += 1
            artigo.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0012_artigo_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_code=migrations.RunPython.noop),
    ]