# Generated by Django 5.2.6 on 2025-10-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0013_populate_artigo_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='highlight_in_menu',
            field=models.BooleanField(default=False, help_text='Marque para destacar este artigo nos menus.'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='is_new',
            field=models.BooleanField(default=False, help_text="Marque para exibir a tag 'Novo' neste artigo."),
        ),
        migrations.AddField(
            model_name='artigo',
            name='show_new_in_category',
            field=models.BooleanField(default=False, help_text="Marque para exibir a tag 'Novo' na categoria e subcategoria deste artigo."),
        ),
    ]
