# Generated by Django 5.2.7 on 2025-10-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0014_artigo_highlight_in_menu_artigo_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='is_new',
            field=models.BooleanField(default=False, help_text="Marque para exibir a tag 'Novo' nesta categoria."),
        ),
    ]
