# Generated by Django 5.2.7 on 2025-10-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0015_categoria_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='is_new',
        ),
    ]
