# Generated by Django 5.2.7 on 2025-10-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0016_remove_categoria_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='show_new_in_category',
        ),
        migrations.AddField(
            model_name='artigo',
            name='show_new_in_category_list',
            field=models.BooleanField(default=False, help_text="Marque para exibir a tag 'Novo' na lista de categorias."),
        ),
        migrations.AddField(
            model_name='artigo',
            name='show_new_in_header',
            field=models.BooleanField(default=False, help_text="Marque para exibir a tag 'Novo' no cabeçalho do artigo."),
        ),
        migrations.AddField(
            model_name='artigo',
            name='show_new_in_subcategory_list',
            field=models.BooleanField(default=False, help_text="Marque para exibir a tag 'Novo' na lista de subcategorias."),
        ),
        migrations.AddField(
            model_name='artigo',
            name='show_new_in_title',
            field=models.BooleanField(default=False, help_text="Marque para exibir a tag 'Novo' no título do artigo."),
        ),
    ]
