# Ordem de exibição para as categorias de nível superior
TOP_LEVEL_ORDER = [
    "Primeiros passos",
    "Funcionalidades",
    "Fiscal",
    "Relatórios",
    "Migrações",
    "Integrações",
    "Apps",
    "Indicadores",
    "PDVgo",
]

# Ordem de exibição para artigos e sub-categorias dentro de cada categoria pai
CATEGORY_ORDER = {
    "Primeiros passos": [
        "Comece por aqui",
        "Instalação e parâmetros iniciais",
        "Cadastro de estação",
        "Cadastro de colaboradores",
        "Cadastro de usuários",
        "Permissões de usuário",
        "Exportação e importação de permissões",
        "Cadastro de taxas do cartão",
        "Tipos de documento",
        "Compensação automática dos cartões",
        "Assistente de formas de pagamento",
        "Assistente de fluxo de operações",
        "Cadastro de caixas",
        "Planos de conta",
        "Backup do banco de dados",
        "Configurações do TEF",
    ],
    "Funcionalidades": [
        "Clientes",
        "Fornecedores",
        "Transportadoras",
        "Produtos e Serviços",
        "Estoque",
        "Etiquetas",
        "Compras",
        "Cotação",
        "Ordem de Serviço",
        "Orçamento",
        "Pedidos",
        "Condicional",
        "Devolução",
        "Comissão",
        "Bonificação",
        "Financeiro",
        "Notificações",
        "Pré venda",
        "Entrega",
        "Delivery Sigecom",
        "Boletos",
        "Solicitação de compra",
        "Controle de promoções",
        "Kit de produtos",
    ],
    "Clientes": [
        "Cadastro de clientes",
        "Desconto padrão e tabela de preço",
        "Controle de aniversariantes",
        "Contratando a utilização de SMS e compra de crédito",
    ],
    "Fornecedores": [
        "Cadastro de fornecedores",
    ],
    "Transportadoras": [
        "Cadastro de transportadoras",
    ],
    "Produtos e Serviços": [
        "Cadastro de produtos",
        "Cadastro de categorias",
        "Cadastro de marcas",
        "Balança",
        "Tabelas de preço",
        "Permissões na tabela de preço",
        "Grade de itens",
        "Cadastro unidades de medida",
        "Função repetir",
        "Cadastro de serviços",
        "Pesquisa de produtos",
        "Gestão de validade",
    ],
    "Gestão de validade": [
        "Gestão de validade",
        "Cadastro de validade",
        "Controle de validade",
    ],
    "Estoque": [
        "Registros (IMEI, Série)",
        "Análise de estoque",
        "Manutenção de estoque",
        "Entradas e saídas gerais",
    ],
    "Registros (IMEI, Série)": [
        "Introdução e configuração de registros de estoque (IMEI, Série)",
        "Manutenção no cadastro de produtos (IMEI, Série)",
        "Fluxos de saída de registros (IMEI, Série)",
        "Fluxo de troca de produtos com registros (IMEI, Série)",
        "Emissão de NF-e de produtos com registros (IMEI, Série)",
        "Fluxo de entrada de registros por compras (IMEI, Série)",
        "Manutenção do estoque com registros (IMEI, Série)",
        "Logs de movimentação de registros (IMEI, Série)",
    ],
    "Etiquetas": [
        "Configurar nova etiqueta",
        "Imprimir etiquetas",
    ],
    "Compras": [
        "Modulo de compras",
        "Compra utilizando arquivo XML",
        "Compra de mercadoria sem arquivo XML",
        "Consultar compras",
    ],
    "Cotação": [
        "Cotação de itens",
        "Consultar cotação",
    ],
    "Ordem de Serviço": [
        "Parametrização da OS",
        "Cadastro de tipos de OS",
        "Cadastro de status de OS",
        "Ordem de serviço",
        "Consulta de OS",
        "Parâmetros adicionais da OS",
        "Controle de objetos",
        "Aviso de vencimento de OS",
    ],
    "Orçamento": [
        "Tipos de orçamento",
        "Status de orçamento",
        "Realizando orçamento",
        "Consulta de orçamentos",
    ],
    "Pedidos": [
        "PDV",
        "Pedido",
        "Troca",
        "Parâmetros de vendas",
        "Consultar vendas",
        "Carrinho",
    ],
    "Condicional": [
        "Condicional",
        "Consultar Condicional",
    ],
    "Devolução": [
        "Devolução",
        "Consultar Devolução",
    ],
    "Comissão": [
        "Configurando o módulo de comissão",
    ],
    "Bonificação": [
        "Bonificação",
        "Consultar Bonificação",
    ],
    "Financeiro": [
        "Caixa",
        "Conferência de caixa",
        "Contas a receber",
        "Contas recebidas",
        "Contas a pagar",
        "Contas pagas",
        "Controle de cheques",
        "Cadastrar conta bancária",
        "Controle bancário",
        "Importação de arquivo OFX",
        "Controle do cartão",
        "Calendário de contas",
        "Controle de acordos",
        "Controle de inadimplência",
    ],
    "Notificações": [
        "Notificações",
    ],
    "Pré venda": [
        "Pré venda",
        "Consultar Pré venda",
    ],
    "Entrega": [
        "Entrega",
    ],
    "Delivery Sigecom": [
        "Configurações de impressão",
        "Cadastros: Area de entrega e Motoboy",
        "Cadastro de complementos",
        "Sigecom Delivery",
        "Relatório de entregas",
    ],
    "Boletos": [
        "Configurando a emissão do boleto",
        "Emissão de boleto bancário",
        "Controle de boletos",
        "Transmissão automática",
    ],
    "Solicitação de compra": [
        "Solicitação de compra",
        "Consultar solicitações",
    ],
    "Controle de promoções": [
        "Controle de promoções",
    ],
    "Kit de produtos": [
        "Funcionamento do kit de produtos",
        "Cadastro de kit de produtos",
        "Desativar e reativar kit de produtos",
        "Clonar kit de produtos",
        "Emissões fiscais do kit de produtos",
    ],
    "Fiscal": [
        "NF-e",
        "SAT",
        "NFS-e",
        "Fechamento fiscal",
        "Tabela IBPT",
        "NFC-e",
    ],
    "NF-e": [
        "Emissão de NF-e",
        "Consulta de NF-e",
    ],
    "SAT": [
        "Configurando S@T",
        "Emissão de S@T",
        "Controle de S@T",
    ],
    "NFS-e": [
        "Emissão de NFS-e",
        "Consulta de NFS-e",
        "Cancelamento de NFS-e",
    ],
    "NFC-e": [
        "Autorização de NFC-e em contingência em massa",
    ],
    "Relatórios": [
        "Vendas",
        "Ordem de serviço",
        "Orçamentos",
        "Compras",
        "Estoque",
        "Balança",
        "Devoluções",
        "Bonificação",
        "Financeiro",
        "Fiscal",
    ],
    "Vendas": [
        "Resumo de vendas",
        "Resumo de faturamentos",
        "Produtos mais, menos e não vendidos",
        "Consumo de clientes",
        "Relação de faturamentos",
        "Análise de faturamentos",
        "Curva ABC de vendas",
        "Ranking de vendas",
    ],
    "Relatorio Ordem de serviço": [
        "Ordem de serviços",
        "Serviços finalizados com comissão",
    ],
    "Relatorio Orçamentos": [
        "Relatório de orçamentos",
    ],
    "Relatorio Compras": [
        "Relatório de compras",
        "Relatório frequência de compras",
    ],
    "Relatorio Estoque": [
        "Relatório conferência de estoque",
        "Relatório balanço de estoque",
        "Análise de movimentações de estoque",
        "Inventário de estoque",
    ],
    "Balança": [
        "Listagem de códigos de balança",
    ],
    "Relatorio Devoluções": [
        "Relatório de devoluções",
    ],
    "Relatorio Bonificação": [
        "Relatório de bonificações",
    ],
    "Relatorio Financeiro": [
        "Relatório de contas a receber",
        "Relatório contas a pagar",
        "Relatório boletos emitidos",
    ],
    "Relatorio Fiscal": [
        "Relatório de NFe",
        "Relatório de operações fiscais",
    ],
    "Migrações": [
        "Migração de clientes",
        "Migração de produtos",
        "Contas a receber",
        "Contas a pagar",
    ],
    "Integrações": [
        "Buscadores de preços",
        "Inteligência fiscal",
        "SigePay - PIX",
        "TEF",
        "Balança de checkout",
        "Clube de promoções - Scanntech",
        "Shipay Itaú - PIX",
    ],
    "Buscadores de preços": [
        "Tanca",
        "Gertec",
    ],
    "Apps": [
        "SigeDash",
    ],
    "SigeDash": [
        "Instalando o SigeDash no celular",
        "Usando o SigeDash no celular",
    ],
    "Indicadores": [
        "O que são os Indicadores?",
        "Faturamento por categoria",
        "Indicador de curva ABC por categoria",
        "Demonstrativo de faturamento",
        "Análise de compras",
        "Demonstrativo de Receitas e Despesas",
    ],
    "PDVgo": [
        "PDV (Vendas no Balcão)",
        "Gestão de Comandas",
    ],
}