# Generated by Django 5.2.8 on 2025-12-08 12:40

import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único gerado automaticamente.', primary_key=True, serialize=False)),
                ('custom_id', models.CharField(blank=True, help_text='ID personalizado (opcional). Se não for fornecido, o ID único será usado na exportação.', max_length=255, null=True, unique=True)),
                ('tipo_aviso', models.CharField(choices=[('popup', 'Pop-up'), ('janela', 'Modo Janela')], default='janela', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', tinymce.models.HTMLField(help_text='O conteúdo da mensagem em formato rich text. Será armazenado como HTML.')),
                ('link_botao', models.URLField(blank=True, help_text="URL para o botão (disponível apenas para 'Modo Janela').", max_length=500)),
                ('texto_botao', models.CharField(blank=True, help_text="Texto do botão (disponível apenas para 'Modo Janela').", max_length=100)),
                ('ativo', models.BooleanField(default=True, help_text='Marque esta opção para incluir o aviso na exportação JSON. Desmarque para ocultá-lo.')),
            ],
            options={
                'verbose_name': 'Aviso Sigecom',
                'verbose_name_plural': 'Avisos Sigecom',
            },
        ),
    ]
