# Generated by Django 5.2.8 on 2025-12-08 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigecom_integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviso',
            name='custom_id',
        ),
        migrations.AlterField(
            model_name='aviso',
            name='id',
            field=models.CharField(help_text='ID sequencial de dois dígitos (ex: 01, 02).', max_length=2, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{2}$', 'O ID deve conter exatamente dois dígitos numéricos.')]),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='mensagem',
            field=models.TextField(help_text='O conteúdo da mensagem em formato RTF, conforme o padrão especificado.'),
        ),
    ]
