# Generated by Django 5.2.8 on 2025-12-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigecom_integration', '0002_remove_aviso_custom_id_alter_aviso_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
