# Generated by Django 5.2.8 on 2025-12-08 13:35

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigecom_integration', '0003_alter_aviso_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='mensagem_rtf',
            field=models.TextField(blank=True, editable=False, help_text='Conteúdo convertido para RTF, gerado automaticamente ao salvar.', verbose_name='Mensagem em formato RTF'),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='mensagem',
            field=tinymce.models.HTMLField(verbose_name='Mensagem (Editor Visual)'),
        ),
    ]
