# Generated by Django 5.2.8 on 2025-12-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigecom_integration', '0004_aviso_mensagem_rtf_alter_aviso_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='tipo_aviso',
            field=models.CharField(choices=[('popup', 'Pop-up'), ('card', 'Card')], default='janela', max_length=10),
        ),
    ]
